### ISSUE TITLE
Get Picard summary metrics from <batch>/02_alignment/bowtie2/target/sample_name.stats file

### ISSUE THREAD

**Issue by teemuronkko** [neurogenomics/EpiCompare#118]
It seems like the newer versions (>= 2.0) of CUT&RUN pipeline do not produce the Picard summary file anymore when a batch is processed with duplicates. Seems like in older versions of the pipeline, this information was stored in the Picard summary file, but now this information is saved in <batch>/02_alignment/bowtie2/target/sample_name.stats file for each sample. Also, when the pipeline is run without duplicates, the stats file does not contain any information on the duplication rate. Would it be possible to include an option to retrieve the information of the duplication rate from this new version of CUT&RUN stats file as well?

**Comment by teemuronkko** [comment]
Seems like these metrics are always stored in /<batch_name>/04_reporting/multiqc/multiqc_data/ in files multiqc_general_stats.txt and multiqc_picard_dups.txt (at least in CUT&RUN version 3.0) as the duplication rate information is included in the multiqc html report, too.

**Comment by bschilder** [comment]
Looking into this now.

**Comment by bschilder** [comment]
@teemuronkko can you paste the command you used here?

**Comment by bschilder** [comment]
`gather_files(type="picard")` would previously search for files matching this pattern (recursively):

"*.target.markdup.MarkDuplicates.metrics.txt$"

We now have several files that contain all or some of this information:

"multiqc_picard_dups.txt"
"multiqc_general_stats.txt"
"mqc_picard_deduplication_1.txt"

**Comment by bschilder** [comment]
Ex
