### ISSUE TITLE
Pull Bioc `RELEASE_3_16`

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/EpiCompare#122]
@serachoi1230 now that Bioc 3.16 has been released, can you pull the new upstream `RELEASE_3_16` branch and then push it to GitHub as a new branch?

**Comment by bschilder** [comment]
Reminding @serachoi1230 to address this

**Comment by serachoi1230** [comment]
thanks @bschilder ! I'll address this sometime next week as I'll have more time

**Comment by serachoi1230** [comment]
@bschilder I tried to do this, but I have some permission issues with my work laptop! I'll have to try again with my personal laptop, which I'll have access to next week :(

**Comment by serachoi1230** [comment]
still having issues with the example report: 

`remote: Error: file larger than 5 Mb.
remote: 
remote:     File name: 'report/EpiCompare_example.html'
remote:     File size: 6.2 Mb
remote: 
remote: Please see Biocondcutor guidelines
remote: https://bioconductor.org/developers/package-guidelines/
remote: 
To git.bioconductor.org:packages/EpiCompare.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git.bioconductor.org:packages/EpiCompare.git'`

Did we come up with a solution?

**Comment by bschilder** [comment]
@serachoi1230 @Al-Murphy let's work through this in a zoom call when we discuss the manuscript edits.

**Comment by Al-Murphy** [comment]
Yeah let's discuss, let me know when!

**Comment by bschilder** [comment]
> report/EpiCompare_example.html

Looks like you accidentally added the *report* folder. This should only be included on GitHub and not be pushed upstream to Bioc.
So, within git, removing the *report* folder from your staged files and then trying to push again should fix this.

**Comment by bschilder** [comment]
> Also add the folder to your .gitignore file so it won't happen again in the future

@Al-Murphy Actually, we shouldnt do this because it will omit it from all future pushes to GitHub as well. Unless there's some way to specify *.gitignore* specific to Bioc.
The example report needs to stored there so it can be rendered in the vignette. Unless we put the report in a separate repo, which im not a fan of since it means not all of EpiCompare's docs are in one place.

**Comment by bschilder** [comment]
```
git rm -r --cache report/
```

**Comment by serachoi1230** [comment]
I should push to `RELEASE_3_17` right?

**Comment by bschilder** [comment]
> I should push to `RELEASE_3_17` right?

@serachoi1230 that's correct, push to the devel version (3.17). You should only push to the release version (currently 3.16) when there's a major bug fix. But all the changes we're making are enhancements, so just push to dev.
