### ISSUE TITLE
push to Bioconductor RELEASE_3_17

### ISSUE THREAD

**Issue by serachoi1230** [neurogenomics/EpiCompare#150]
Hi @bschilder and @Al-Murphy,

I've tried to push to RELEASE_3_17, but get the error:

``` 
fatal: couldn't find remote ref refs/heads/RELEASE_3_17
```
Is this because the RELEASE_3_17 branch hasn't been created in Bioconductor?

**Comment by Al-Murphy** [comment]
Yeah exactly! So 3.17 hasn't been released yet, it is the dev branch which corresponds to the master branch. You just do `git push upstream master` make sure to increment the minor version (Z in X.Y.Z) in your description file or it will have no effect

**Comment by bschilder** [comment]
@serachoi1230 for reference, Bioc will soon (March 8th) rename their upstream `master` branch to `devel`. 
https://bioconductor.github.io/biocblog/posts/2023-03-01-transition-to-devel/

See here for our instructions on how to handle this:
https://github.com/neurogenomics/labwiki/wiki/Creating-a-Bioconductor-package#what-to-expect-after-submitting-to-bioconductor
