### ISSUE TITLE
EpiCompare failing on Bioc Windows

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/EpiCompare#153]
## 1. Bug description

Failing on Windows Bioc server:
https://bioconductor.org/packages/release/bioc/html/EpiCompare.html
http://bioconductor.org/checkResults/release/bioc-LATEST/EpiCompare/palomino3-buildsrc.html

### Console output 

```
##############################################################################


* checking for file 'EpiCompare/DESCRIPTION' ... OK
* preparing 'EpiCompare':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building 'EpiCompare.Rmd' using rmarkdown
Quitting from lines 193-210 (EpiCompare.Rmd) 
Error: processing vignette 'EpiCompare.Rmd' failed with diagnostics:
Parser error: while parsing a block mapping at line 1, column 1 did not find expected key at line 1, column 45
--- failed re-building 'EpiCompare.Rmd'

--- re-building 'docker.Rmd' using rmarkdown
--- finished re-building 'docker.Rmd'

--- re-building 'example_report.Rmd' using rmarkdown
--- finished re-building 'example_report.Rmd'

SUMMARY: processing the following file failed:
  'EpiCompare.Rmd'

Error: Vignette re-building failed.
Execution halted

```

### Expected behaviour   

Passes all Bioc checks.

## 2. Reproducible example   

Knitting the following file:
https://github.com/neurogenomics/EpiCompare/blob/master/vignettes/EpiCompare.Rmd

## 3. Session info

http://bioconductor.org/checkResults/release/bioc-LATEST/EpiCompare/palomino3-buildsrc.html

**Comment by bschilder** [comment]
@serachoi1230 it looks like `EpiCompare` is now failing on both Bico 3.17 and 3.18. If we don't fix it, it will become deprecated automatically. 

Let us know if you think you'll be able to maintain `EpiCompare`. If not, let's arrange to transfer maintainership to someone in the neurogenomics lab so we can have permissions to push upstream. Thanks!

**Comment by bschilder** [comment]
@NathanSkene @Al-Murphy, we should have a broader discussion about how the Neurogenomics Lab plans to maintain its software in the long run. i.e. who gets assigned Maintainer status once someone leaves the lab.

**Comment by serachoi1230** [comment]
Hey @bschilder! Thanks for this and sorry for this super late reply! I think it would be best to transfer the maintainership as it's getting more and more difficult for me to maintain EpiCompare sadly!

Please could you let me know who I'm handing over to and what needs to be done?

Thanks so much again Brian!

**Comment by NathanSkene** [comment]
I’ll have a chat with Thomas about him taking over

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bschilder** [comment]
Great idea, thanks @NathanSkene !

**Comment by bschilder** [comment]
> Hey @bschilder! Thanks for this and sorry for this super late reply! I think it would be best to transfer the maintainership as it's getting more and more difficult for me to maintain EpiCompare sadly!
> 
> Please could you let me know who I'm handing over to and what needs to be done?
> 
> Thanks so much again Brian!

No worries @serachoi1230 , I think it's totally reasonable for you to focus on your current work rather than maintaining this indefinitely. We may come you occasionally if there's parts of the code we don't quite understand, but we'll transition maintainership to dedicated personnel within the lab.

@Al-Murphy do you know if there's a proper way to transfer maintainership? I've seen people do this by emailing the general bioc-devel@r-project.org mailing list, but not sure if there's a more official way to do it.

**Comment by Al-Murphy** [comment]
I actually think you have to email about it for them to transfer on their end, doesn't seem to be much online about it?

**Comment by bschilder** [comment]
Cool, @Tomrrr1 and @NathanSkene are meeting tomorrow to discuss transiting maintainership tomorrow. In the meantime, here are some important notes from the Bioc team about the upcoming release:

Send to the bioc devel mailing list on Oct 23 2023:
> We are still on track for Bioconductor Release 3.18 for this Wednesday October 25th.  This means that tonight is the last day to commit changes to the devel branch before creation of the RELEASE_3_18 versions of your packages.  And any changes you make to your packages at this point will not be reflected in a build report before we branch.

>There will be a temporary code freeze tomorrow morning (EST)  while the branching for RELEASE_3_18 occurs automatically by the core team.  You will receive emails when the freeze occurs and when commits to the branches can resume.

> As clarification,  you will still be able to commit to the release 3.18 branch and the devel branch throughout the next release cycle. But any packages that have not been fixed for failures or bugs in devel would then have to be fixed/uploaded to both the RELEASE_3_18 branch and the devel branch after tomorrow morning. Any package that remains broken in release would also be candidates for deprecation in 3.19

**Comment by bschilder** [comment]
@serachoi1230 could you please send an email to the Bioc team via bioc-devel@r-project.org and request them to transfer maintainership of `EpiCompare` from you to:

Tom Roberts
**GitHub username**: @Tomrrr1
**Email**: zcbttr2@ucl.ac.uk

**Comment by serachoi1230** [comment]
Hi @Tomrrr1, do you have BiocCredentials account?

**Comment by Tomrrr1** [comment]
Hi Sera, No I do not have an account. Is there a link I can use to setup one?

**Comment by bschilder** [comment]
> Hi @serachoi1230, No I do not have an account. Is there a link I can use to setup one?

Here you go @Tomrrr1 : https://git.bioconductor.org/BiocCredentials/login/?next=/BiocCredentials/

**Comment by serachoi1230** [comment]
No worries @Tomrrr1 @bschilder ! I emailed Bioconductor and they said they'll create an account for you and give access to EpiCompare. I've cc'ed you in the email

**Comment by Tomrrr1** [comment]
Great! thanks @serachoi1230 @bschilder

**Comment by HDash** [comment]
All workflows passing as of commit c2719d6dba5a409c2b12f69a6bd528a8e0c2d558
