### ISSUE TITLE
Run `plot_chromHMM` example

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/EpiCompare#63]
I noticed the `plot_chromHMM` example was commented out. Is there a particular reason this? If not, would be best to run all examples when possible to ensure they work.

**Comment by serachoi1230** [comment]
I think I commented it out to reduce the CMD check running time. When I was preparing EpiCompare for Bioconductor submission, the running time exceeded 15mins, but I can change that!

**Comment by bschilder** [comment]
I actually added the example plus some new features to `plot_chromHMM`. I've documented all changes in the [NEWS file](https://github.com/neurogenomics/EpiCompare/blob/master/NEWS.md) but let me know if you have any questions.

Looks like it's taking 8-9 min to run CRAN checks on all OS tested on GHA. So I think it should be ok now.
So if there's any other exported functions without running examples, would be good if you could add those too.
