### ISSUE TITLE
`compute_corr()`: Benchmark how bin sizes affect correlations

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/EpiCompare#94]
i think it would be good to do some benchmarking to see how bin size affects correlations. we could start with a very small bin size (25bp?) and use that as the “ground truth”, then gradually increase bin size and  see how close it is to that.

This will be partly data-dependent, but at least this will give us some idea of a sensible default.

If you have a chance, would you mind trying something like this @Al-Murphy ?

**Comment by Al-Murphy** [comment]
I believe it's hard to define the 'correct' answer for such benchmarking. What you notice is correlation values will increase as you increase bin size. The difference I noted between bin size of 25 and 100bp on the example data in EpiCompare was ~0.01 increase in correlation values

I didn't test larger bins e.g. 1000 but I set the examples in EpiCompare to run at that size as it made it very fast. Biologically I think once you set the size to much larger than the size of peaks you will lose a lot of signal and thus the benefit of even working out the correlation.

For example, if you were to make each peak span entire chromosomes, you'd have near perfect correlation, but it wouldn't mean anything
